<?php
function dt_adwords_remarketing_page_build( &$page ) {
    $page['page_bottom']['adwords_remarketing_code'] = array(
        '#type' => 'markup',
        '#markup' => '

    <!-- Start Google Adwords Remarketing code -->
    <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 997973119;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/997973119/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
    </noscript>
    <!-- End Google Adwords Remarketing code -->

        ',
    );
}